Using | instead of >- to attempt to resolve YAML Parser error
Still got the same error for multiline values when using >-

YAMLParseError: Implicit keys need to be on a single line at line 6, column 1:

  ghcr.io/everest/everest-demo/mqtt-server:0.0.16
ghcr.io/everest/everest-demo/mqtt-server:latest
^