Update cicd.yaml
Got an error but values are being passed between steps of matrix jobs. Perhaps missing double quotes was the problem, let's see if that resolves it.

------
Got this error:

Error: Outputs should be valid YAML
---------------------
host_namespace: ghcr.io/everest/everest-demo
image: mqtt-server
context: ./mosquitto
tags: ghcr.io/everest/everest-demo/mqtt-server:0.0.16
ghcr.io/everest/everest-demo/mqtt-server:latest
labels: org.opencontainers.image.created=2024-07-01T17:35:09.789Z

---------------------
YAMLParseError: Implicit keys need to be on a single line at line 5, column 1:

tags: ghcr.io/everest/everest-demo/mqtt-server:0.0.16
ghcr.io/everest/everest-demo/mqtt-server:latest
^

----------